### ISSUE TITLE
Build the data dashboard page. 

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#591]
@ketankartoza we need to build the visualization dashboard page.  
please not the charts required as some of the visualisations are shown on the map view. but see required filters and visualisation below. 

![Image](https://github.com/kartoza/sawps/assets/77841514/b50167ec-0421-4760-b53f-fda431adb131)

## Sub Tasks 
- [x] #659
- [x] #660
- [x] #661
- [x] #662
- [x] #663
- [x] #664

**Comment by amyburness** [comment]
Please use charts.js so make the charts: 
we need to visualise the following as per the user requirments.


![Image](https://github.com/kartoza/sawps/assets/77841514/d33bdb48-ec5f-4869-af95-e21a6e46e088)

**Comment by ketankartoza** [comment]
## SubTask

- [ ] Species population count per month for property.
- [ ] Activity data as % of total population.
- [ ] Species activity data as total by method.
- [ ] Number of population per population category.
- [ ] Species population total and density for property.
- [ ] Number of properties per population category.

**Comment by amyburness** [comment]
@ketankartoza I am updating this ticket as the main ticket. Please update the sub-tickets as required with screenshots.

The user must be able to see all properties in their organization at first and then filter using the properties list to species list and all the other filters. 

see the video:
- see the updates to the filter panel with multi-selector dropdowns for species and property allowing the user to filter down the data.
- see the updated visualization, particularly the counts per activity.  

https://github.com/kartoza/sawps/assets/77841514/cd231d6d-ab05-4d09-9b53-7944f8480300
Update to the filter panel. 
![image](https://github.com/kartoza/sawps/assets/77841514/4291f1b3-1e5d-4d18-a516-df0572ce4caa)
Graphs 
![image](https://github.com/kartoza/sawps/assets/77841514/4899bd87-6c6d-4abc-852b-65440d8b4272)
Graphs
![image](https://github.com/kartoza/sawps/assets/77841514/9a6cd4df-94b2-430d-9362-700d9fb7202e)
Graphs for filtered by species. 
![image](https://github.com/kartoza/sawps/assets/77841514/d091dedc-2d42-4d14-895e-d440e70c101b)

**Comment by LunaAsefaw** [comment]
Subtickets implemented
