### ISSUE TITLE
Fix filters on 'Map' tab

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#851]
Currently the property and species filter on the 'data upload' tab work. However, none of the filters work on the 'map' tab' and none of the spatial filters work on the other tabs.

Additionally, activity has 'contraception' but there is no activity type called contraception in the database so the values to be stored in the filters need to be pulled from values stored in the database.

Lastly, the data filters set need to apply to the data displayed in the side panel pop up too.

**Comment by danangmassandy** [comment]
Related ticket #460. I need to apply the filter to generate the dynamic layer.

**Comment by danangmassandy** [comment]
TODO:

- [ ] Filter by property on map (zoom to bbox of properties) #933 
- [ ] Filter by species on map tab (Draw Choropleth Layer) #934 
- [ ] See property on a higher zoom level (Display property as points) #812
